# Generated by Django 3.2.24 on 2024-02-07 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="ToDictMixin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                ("todictmixin_ptr", models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to="django_extended_models.todictmixin")),
            ],
            bases=("django_extended_models.todictmixin",),
        ),
    ]
