# Generated by Django 3.2.24 on 2024-02-07 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_extended_models", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatedModel1",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("related_field1", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="RelatedModel2",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("related_field2", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="RelatedModel3",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "related_field1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_extended_models_tests.relatedmodel1",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="YourModel",
            fields=[
                (
                    "todictmixin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_extended_models.todictmixin",
                    ),
                ),
                ("field1", models.CharField(max_length=100)),
                ("field2", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField(blank=True, null=True)),
                (
                    "related_field1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_extended_models_tests.relatedmodel1",
                    ),
                ),
                (
                    "related_field2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_extended_models_tests.relatedmodel2",
                    ),
                ),
                (
                    "related_field3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_extended_models_tests.relatedmodel3",
                    ),
                ),
            ],
            bases=("django_extended_models.todictmixin", models.Model),
        ),
    ]
